server:
  port: 1019
spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: us
          predicates:
            - Path=/users/**
          uri:  lb://app-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:4196/eureka